export const datalist = [
    {
      id: "1",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Frutti Di Mare",
      title: "jauhelihaa ja paprikaa",
      price: "7,99 €",
    },
    {
      id: "2",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Bolognese",
      title: "jauhelihaa ja",
      price: "10,99 €",
    },
    {
      id: "3",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Frutti Di Mare",
      title: "jauhelihaa ja paprikaa",
      price: "7,99 €",
    },
    {
      id: "4",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Bolognese",
      title: "jauhelihaa ja",
      price: "10,99 €",
    },
    {
      id: "6",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Frutti Di Mare",
      title: "jauhelihaa ja paprikaa",
      price: "7,99 €",
    },
    {
      id: "7",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Bolognese",
      title: "jauhelihaa ja",
      price: "10,99 €",
    },
    {
      id: "8",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Bolognese",
      title: "jauhelihaa ja",
      price: "10,99 €",
    },
    {
      id: "9",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Frutti Di Mare",
      title: "jauhelihaa ja paprikaa",
      price: "7,99 €",
    },
    {
      id: "10",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Frutti Di Mare",
      title: "jauhelihaa ja paprikaa",
      price: "7,99 €",
    },
    {
      id: "11",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Frutti Di Mare",
      title: "jauhelihaa ja paprikaa",
      price: "7,99 €",
    },
    {
      id: "12",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Bolognese",
      title: "jauhelihaa ja",
      price: "10,99 €",
    },
    {
      id: "13",
      images: "/images/CheckoutPageImage/pizza.svg",
      name: "Bolognese",
      title: "jauhelihaa ja",
      price: "10,99 €",
    },
  ];
  